services:
  directus:
    image: "directus/directus:latest"
    volumes:
      - ./extensions:/directus/extensions
      - ./templates:/directus/templates
      - ./uploads:/directus/uploads
    environment:
      - SECRET=0193e9fe-9ec0-7576-a018-6f59696f4287
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=1234
      - DB_CLIENT=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_DATABASE=directus
      - DB_USER=directus
      - DB_PASSWORD=directus
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - "PUBLIC_URL=https://cms.yourdomain.dom"
      - "PASSWORD_RESET_URL_ALLOW_LIST=https://cms.yourdomain.dom"
      - SESSION_COOKIE_DOMAIN=yourdomain.dom
      - SESSION_COOKIE_TTL=1d
      - SESSION_COOKIE_SECURE=true
      - SESSION_COOKIE_SAME_SITE=Strict
      - SESSION_COOKIE_NAME=session_token
      - SESSION_REFRESH_GRACE_PERIOD=10s
      - CORS_ENABLED=true
      - "CORS_ORIGIN=https://frontend.yourdomain.dom"
      - CORS_METHODS=GET,POST,PATCH,DELETE
      - CORS_ALLOWED_HEADERS=Content-Type,Authorization
      - CORS_EXPOSED_HEADERS=Content-Range
      - CORS_CREDENTIALS=true
      - CORS_MAX_AGE=18000
      - TELEMETRY=false
      - WEBSOCKETS_ENABLED=false
      - WEBSOCKETS_HEARTBEAT_ENABLED=false
      - WEBSOCKETS_REST_ENABLED=false
    healthcheck:
      test:
        - CMD
        - wget
        - "-q"
        - "--spider"
        - "http://127.0.0.1:8055/admin/login"
      interval: 5s
      timeout: 20s
      retries: 10
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
  postgresql:
    image: "postgis/postgis:16-3.4-alpine"
    platform: linux/amd64
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=directus
      - POSTGRES_PASSWORD=directus
      - POSTGRES_DB=directus
    healthcheck:
      test:
        - CMD-SHELL
        - "pg_isready -U directus -d directus"
      interval: 5s
      timeout: 20s
      retries: 10
  redis:
    image: "redis:7-alpine"
    command: "redis-server --appendonly yes"
    volumes:
      - ./database/redis:/data
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 20s
      retries: 10
